import type { Quote, Achievement, Certificate, ThemeConfig } from '@/types'

// ─── Mock Quotes ──────────────────────────────────────────────────────────────

export const MOCK_QUOTES: Quote[] = [
  {
    id: '1',
    text: 'Great things are built one commit at a time.',
    author: 'CVWT Community',
    category: 'Coding',
    reading_time_seconds: 10,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    text: 'Design is not just what it looks like and feels like. Design is how it works.',
    author: 'Steve Jobs',
    category: 'Design',
    reading_time_seconds: 15,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    text: 'The best way to predict the future is to invent it.',
    author: 'Alan Kay',
    category: 'Innovation',
    reading_time_seconds: 12,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    text: 'A leader is one who knows the way, goes the way, and shows the way.',
    author: 'John Maxwell',
    category: 'Leadership',
    reading_time_seconds: 14,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    text: 'Focus on being productive instead of busy.',
    author: 'Tim Ferriss',
    category: 'Productivity',
    reading_time_seconds: 10,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    text: 'Alone we can do so little; together we can do so much.',
    author: 'Helen Keller',
    category: 'Community',
    reading_time_seconds: 12,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    text: 'Code is like humor. When you have to explain it, it\'s bad.',
    author: 'Cory House',
    category: 'Coding',
    reading_time_seconds: 12,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    text: 'Simplicity is the ultimate sophistication.',
    author: 'Leonardo da Vinci',
    category: 'Design',
    reading_time_seconds: 10,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    text: 'Innovation distinguishes between a leader and a follower.',
    author: 'Steve Jobs',
    category: 'Innovation',
    reading_time_seconds: 12,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    text: 'Your time is limited, don\'t waste it living someone else\'s life.',
    author: 'Steve Jobs',
    category: 'Leadership',
    reading_time_seconds: 14,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    text: 'It\'s not about having time. It\'s about making time.',
    author: 'Unknown',
    category: 'Productivity',
    reading_time_seconds: 10,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '12',
    text: 'Coming together is a beginning, staying together is progress, working together is success.',
    author: 'Henry Ford',
    category: 'Community',
    reading_time_seconds: 18,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '13',
    text: 'First, solve the problem. Then, write the code.',
    author: 'John Johnson',
    category: 'Coding',
    reading_time_seconds: 12,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '14',
    text: 'Every great design begins with an even better story.',
    author: 'Lorinda Mamo',
    category: 'Design',
    reading_time_seconds: 12,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '15',
    text: 'Stay hungry, stay foolish.',
    author: 'Steve Jobs',
    category: 'Innovation',
    reading_time_seconds: 8,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
]

// ─── Mock Achievements ────────────────────────────────────────────────────────

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: '1',
    member_name: 'Alex Rivera',
    achievement_title: 'Top Community Builder',
    achievement_description: 'Built 3 open source tools that power our community platform',
    category: 'Developer',
    card_dimension: 'instagram',
    theme: 'cvwt-neon',
    likes: 47,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '2',
    member_name: 'Maya Chen',
    achievement_title: 'Design Excellence Award',
    achievement_description: 'Redesigned the CVWT brand identity with stunning precision',
    category: 'Designer',
    card_dimension: 'linkedin',
    theme: 'purple-galaxy',
    likes: 89,
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: '3',
    member_name: 'Jordan Smith',
    achievement_title: 'Innovation Catalyst',
    achievement_description: 'Introduced AI workflows that saved 40+ hours per week',
    category: 'Innovator',
    card_dimension: 'twitter',
    theme: 'cyber-dark',
    likes: 63,
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
]

// ─── Mock Certificates ────────────────────────────────────────────────────────

export const MOCK_CERTIFICATES: Certificate[] = [
  {
    id: '1',
    recipient_name: 'Sam Torres',
    award_type: 'Top Contributor',
    date: '2024-01-15',
    has_signature: true,
    signatory_name: 'Dr. Sarah Kim',
    signatory_title: 'CVWT Community Lead',
    theme: 'cvwt-neon',
    likes: 34,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '2',
    recipient_name: 'Riley Johnson',
    award_type: 'Community Impact',
    date: '2024-01-20',
    has_signature: true,
    signatory_name: 'Marcus Lee',
    signatory_title: 'CVWT Design Fest Director',
    theme: 'glassmorphism',
    likes: 56,
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
]

// ─── Theme Configs ────────────────────────────────────────────────────────────

export const THEMES: ThemeConfig[] = [
  {
    id: 'cvwt-neon',
    name: 'CVWT Neon',
    description: 'Signature purple & pink neon',
    gradient: 'linear-gradient(135deg, #8B5CF6 0%, #EC4899 100%)',
    cardGradient: 'linear-gradient(135deg, #1a0533 0%, #2d0b4e 50%, #1a1035 100%)',
    textColor: '#FFFFFF',
    accentColor: '#8B5CF6',
    borderColor: 'rgba(139, 92, 246, 0.3)',
  },
  {
    id: 'purple-galaxy',
    name: 'Purple Galaxy',
    description: 'Deep space indigo vibes',
    gradient: 'linear-gradient(135deg, #4c1d95 0%, #7c3aed 50%, #1e1b4b 100%)',
    cardGradient: 'linear-gradient(135deg, #1e0533 0%, #2d1b69 50%, #0f0f3d 100%)',
    textColor: '#E9D5FF',
    accentColor: '#A78BFA',
    borderColor: 'rgba(167, 139, 250, 0.3)',
  },
  {
    id: 'cyber-dark',
    name: 'Cyber Dark',
    description: 'Midnight cyber aesthetic',
    gradient: 'linear-gradient(135deg, #06b6d4 0%, #3B82F6 100%)',
    cardGradient: 'linear-gradient(135deg, #000511 0%, #0a0a1a 50%, #000c1f 100%)',
    textColor: '#BAE6FD',
    accentColor: '#38BDF8',
    borderColor: 'rgba(56, 189, 248, 0.3)',
  },
  {
    id: 'glassmorphism',
    name: 'Glassmorphism',
    description: 'Frosted glass luxury',
    gradient: 'linear-gradient(135deg, rgba(139,92,246,0.6) 0%, rgba(236,72,153,0.6) 100%)',
    cardGradient: 'linear-gradient(135deg, rgba(255,255,255,0.1) 0%, rgba(255,255,255,0.05) 100%)',
    textColor: '#FFFFFF',
    accentColor: '#C4B5FD',
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  {
    id: 'minimal-white',
    name: 'Minimal White',
    description: 'Clean & professional',
    gradient: 'linear-gradient(135deg, #6366f1 0%, #8B5CF6 100%)',
    cardGradient: 'linear-gradient(135deg, #ffffff 0%, #f5f3ff 100%)',
    textColor: '#1e1b4b',
    accentColor: '#7C3AED',
    borderColor: 'rgba(109, 40, 217, 0.2)',
  },
]

// ─── Category Colors & Icons ──────────────────────────────────────────────────

export const CATEGORY_COLORS: Record<string, string> = {
  Developer: '#3B82F6',
  Designer: '#EC4899',
  'Community Builder': '#10B981',
  Contributor: '#F59E0B',
  Innovator: '#8B5CF6',
  Coding: '#3B82F6',
  Design: '#EC4899',
  Innovation: '#8B5CF6',
  Leadership: '#F59E0B',
  Productivity: '#10B981',
  Community: '#06B6D4',
}

export const CATEGORY_EMOJIS: Record<string, string> = {
  Developer: '⚡',
  Designer: '✦',
  'Community Builder': '🌐',
  Contributor: '🔥',
  Innovator: '🚀',
  Coding: '💻',
  Design: '🎨',
  Innovation: '💡',
  Leadership: '👑',
  Productivity: '⚡',
  Community: '🤝',
}
