import { motion } from 'framer-motion'
import { Image } from 'lucide-react'
import { GalleryShowcase } from '@/components/gallery/GalleryShowcase'
import type { Achievement, Certificate, GalleryFilter } from '@/types'

interface GalleryPageProps {
  achievements: Achievement[]
  certificates: Certificate[]
  filter: GalleryFilter
  onFilterChange: (f: GalleryFilter) => void
  loading: boolean
  error: string | null
}

export function GalleryPage({
  achievements,
  certificates,
  filter,
  onFilterChange,
  loading,
  error,
}: GalleryPageProps) {
  const total = achievements.length + certificates.length

  return (
    <main className="relative min-h-screen pt-28 px-4 pb-20 max-w-7xl mx-auto">

      {/* ── Header ──────────────────────────────────────────────────────────────── */}
      <div className="mb-10 flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4">
        <div>
          <motion.h1
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            className="font-display text-3xl md:text-4xl font-extrabold text-white mb-2"
          >
            Community Gallery
          </motion.h1>
          <p className="text-cvwt-muted text-sm max-w-xl">
            Achievement cards, certificates, and quote cards generated by the CVWT community.
          </p>
        </div>
        <div className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-cvwt-muted w-fit">
          <Image size={14} aria-hidden="true" />
          <span>
            <strong className="text-white">{total}</strong> creations
          </span>
        </div>
      </div>

      {/* ── Gallery ─────────────────────────────────────────────────────────────── */}
      <GalleryShowcase
        achievements={achievements}
        certificates={certificates}
        filter={filter}
        onFilterChange={onFilterChange}
        loading={loading}
        error={error}
      />
    </main>
  )
}
